[client]
toolbarMode = "viewer"
showErrorDetails = false

[server]
headless = true

[runner]
magicEnabled = true
fastReruns = true

[browser]
gatherUsageStats = false

[ui]
hideTopBar = true
hideSidebarNav = false