[client]
toolbarMode = "viewer"

showErrorDetails = true

[theme]
# Optional: Customize the theme
# primaryColor = "#FF6B6B"
# backgroundColor = "#FFFFFF"
# secondaryBackgroundColor = "#F0F2F6"
# textColor = "#262730"
# font = "sans serif"  # Options: "sans serif", "serif", "monospace"

[runner]
magicEnabled = true

fastReruns = true